

include ./Makefile.conf
#CC = gcc-multilib
#CXX = g++-multilib
#LD = $(CXX)
OUTDIR = ../lib/gnu_32
TITLE=libIPSF-100
CFLAGS=-m32 -L/usr/libx32/ -lstdc++
LDFLAGS= -shared -fPIC -ldl -m32
include ./Makefile.def
LIB = ../lib/gnu_32/libcrypto.a