var hierarchy =
[
    [ "_ft_device_list_info_node", "struct__ft__device__list__info__node.html", null ],
    [ "_FTCOMSTAT", "struct___f_t_c_o_m_s_t_a_t.html", null ],
    [ "_FTDCB", "struct___f_t_d_c_b.html", null ],
    [ "_FTTIMEOUTS", "struct___f_t_t_i_m_e_o_u_t_s.html", null ],
    [ "_tagHEADER_WRITE_PACKET", "struct__tag_h_e_a_d_e_r___w_r_i_t_e___p_a_c_k_e_t.html", null ],
    [ "_tagHEADER_WRITE_PURE_PACKET", "struct__tag_h_e_a_d_e_r___w_r_i_t_e___p_u_r_e___p_a_c_k_e_t.html", null ],
    [ "_tagPROCESSINFO", "struct__tag_p_r_o_c_e_s_s_i_n_f_o.html", null ],
    [ "_tagREGVALUEINFO", "struct__tag_r_e_g_v_a_l_u_e_i_n_f_o.html", null ],
    [ "_tagSAMPLE_FUNCTIONS", "struct__tag_s_a_m_p_l_e___f_u_n_c_t_i_o_n_s.html", null ],
    [ "_tagSECTOR", "struct__tag_s_e_c_t_o_r.html", null ],
    [ "_tagST_AC_CONDITION", "struct__tag_s_t___a_c___c_o_n_d_i_t_i_o_n.html", null ],
    [ "_tagST_DATA_128", "struct__tag_s_t___d_a_t_a__128.html", null ],
    [ "_tagST_DATA_16", "struct__tag_s_t___d_a_t_a__16.html", null ],
    [ "_tagST_DATA_32", "struct__tag_s_t___d_a_t_a__32.html", null ],
    [ "_tagST_DATA_64", "struct__tag_s_t___d_a_t_a__64.html", null ],
    [ "_tagST_DIVERSIFY_PARAM", "struct__tag_s_t___d_i_v_e_r_s_i_f_y___p_a_r_a_m.html", null ],
    [ "_tagST_ECC_PRV", "struct__tag_s_t___e_c_c___p_r_v.html", null ],
    [ "_tagST_ECC_PUBLIC", "struct__tag_s_t___e_c_c___p_u_b_l_i_c.html", null ],
    [ "_tagST_ECC_PUBLIC_COMPRESS", "struct__tag_s_t___e_c_c___p_u_b_l_i_c___c_o_m_p_r_e_s_s.html", null ],
    [ "_tagST_ECDH_IV", "struct__tag_s_t___e_c_d_h___i_v.html", null ],
    [ "_tagST_ECDH_KEY_BLOCK", "struct__tag_s_t___e_c_d_h___k_e_y___b_l_o_c_k.html", null ],
    [ "_tagST_ECDH_PRE_MASTER_SECRET", "struct__tag_s_t___e_c_d_h___p_r_e___m_a_s_t_e_r___s_e_c_r_e_t.html", null ],
    [ "_tagST_ECDH_RANDOM", "struct__tag_s_t___e_c_d_h___r_a_n_d_o_m.html", null ],
    [ "_tagST_ECIES", "struct__tag_s_t___e_c_i_e_s.html", null ],
    [ "_tagST_G3_IO_LIB_FUNCTIONS", "struct__tag_s_t___g3___i_o___l_i_b___f_u_n_c_t_i_o_n_s.html", null ],
    [ "_tagST_IV", "struct__tag_s_t___i_v.html", null ],
    [ "_tagST_KEY_SECTOR", "struct__tag_s_t___k_e_y___s_e_c_t_o_r.html", null ],
    [ "_tagST_KEY_VALUE", "struct__tag_s_t___k_e_y___v_a_l_u_e.html", null ],
    [ "_tagST_RW_DATA", "struct__tag_s_t___r_w___d_a_t_a.html", null ],
    [ "_tagST_RW_DATA_WITH_IV", "struct__tag_s_t___r_w___d_a_t_a___w_i_t_h___i_v.html", null ],
    [ "_tagST_RW_DATA_WITH_IV_MAC", "struct__tag_s_t___r_w___d_a_t_a___w_i_t_h___i_v___m_a_c.html", null ],
    [ "_tagST_RW_DATA_WITH_MASK", "struct__tag_s_t___r_w___d_a_t_a___w_i_t_h___m_a_s_k.html", null ],
    [ "_tagST_SET_UP_VALUE", "struct__tag_s_t___s_e_t___u_p___v_a_l_u_e.html", null ],
    [ "_tagST_SETUP_CORE", "struct__tag_s_t___s_e_t_u_p___c_o_r_e.html", null ],
    [ "_tagST_SIGN_ECDSA", "struct__tag_s_t___s_i_g_n___e_c_d_s_a.html", null ],
    [ "_tagST_SIGN_HMAC", "struct__tag_s_t___s_i_g_n___h_m_a_c.html", null ],
    [ "_tagST_SIGN_SYMM", "struct__tag_s_t___s_i_g_n___s_y_m_m.html", null ],
    [ "_tagST_TLS_HAND_HANDSHAKE_DIGEST", "struct__tag_s_t___t_l_s___h_a_n_d___h_a_n_d_s_h_a_k_e___d_i_g_e_s_t.html", null ],
    [ "_tagST_TLS_INTER_HEADER", "struct__tag_s_t___t_l_s___i_n_t_e_r___h_e_a_d_e_r.html", null ],
    [ "_tagST_TLS_INTER_HEADER_WITHOUT_SIZE", "struct__tag_s_t___t_l_s___i_n_t_e_r___h_e_a_d_e_r___w_i_t_h_o_u_t___s_i_z_e.html", null ],
    [ "_tagTLS_INTER_HEADER", "struct__tag_t_l_s___i_n_t_e_r___h_e_a_d_e_r.html", null ],
    [ "_tagVAR_BYTES", "struct__tag_v_a_r___b_y_t_e_s.html", null ],
    [ "_tagWRITE_PACKET", "struct__tag_w_r_i_t_e___p_a_c_k_e_t.html", null ],
    [ "_tagWRITE_PURE_PACKET", "struct__tag_w_r_i_t_e___p_u_r_e___p_a_c_k_e_t.html", null ],
    [ "CFILELOCK", "class_c_f_i_l_e_l_o_c_k.html", null ],
    [ "Cg3_api_library", "class_cg3__api__library.html", null ],
    [ "neocolib::CMem", "classneocolib_1_1_c_mem.html", [
      [ "neocolib::CARRAY< T >", "classneocolib_1_1_c_a_r_r_a_y.html", null ],
      [ "neocolib::CMANMEM< T >", "classneocolib_1_1_c_m_a_n_m_e_m.html", null ]
    ] ],
    [ "CMUTEX", "class_c_m_u_t_e_x.html", null ],
    [ "CSerialBASE", "class_c_serial_b_a_s_e.html", [
      [ "CSerialRS232", "class_c_serial_r_s232.html", null ]
    ] ],
    [ "FT4222_Version", "struct_f_t4222___version.html", null ],
    [ "ft_eeprom_2232", "structft__eeprom__2232.html", null ],
    [ "ft_eeprom_2232h", "structft__eeprom__2232h.html", null ],
    [ "ft_eeprom_232b", "structft__eeprom__232b.html", null ],
    [ "ft_eeprom_232h", "structft__eeprom__232h.html", null ],
    [ "ft_eeprom_232r", "structft__eeprom__232r.html", null ],
    [ "ft_eeprom_4232h", "structft__eeprom__4232h.html", null ],
    [ "ft_eeprom_header", "structft__eeprom__header.html", null ],
    [ "ft_eeprom_x_series", "structft__eeprom__x__series.html", null ],
    [ "ft_program_data", "structft__program__data.html", null ],
    [ "neocolib::NeoCoLib", "classneocolib_1_1_neo_co_lib.html", null ],
    [ "NeoSystemLib", "class_neo_system_lib.html", null ],
    [ "SPI_Slave_Header", "struct_s_p_i___slave___header.html", null ]
];